---
- name: python3 is installed
  become: true
  apt:
      name: python3
      state: latest

- name: pip is installed
  become: true
  apt:
    name: python3-pip
    state: latest

- name: python packages are installed
  become: true
  pip:
      name: "{{ item.name }}=={{ item.version }}"
      executable: pip3
  loop: "{{ python_packages }}"
